draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: auto
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  svg_extra_style: ""
  footer_text: Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AltGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: "{mods}+{key}"
    mod_combiner: "{mod_1}+{mod_2}"
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  raw_binding_map:
    "&soft_off": ""
    "&caps_word": "󰪛"
    "&to 0": ""
    "&mmv MOVE_LEFT": "󰍽 "
    "&mmv MOVE_DOWN": "󰍽 "
    "&mmv MOVE_UP": "󰍽 "
    "&mmv MOVE_RIGHT": "󰍽 "
    "&msc SCRL_LEFT": "󰍽 ⇇"
    "&msc SCRL_DOWN": "󰍽 ⇊"
    "&msc SCRL_UP": "󰍽 ⇈"
    "&msc SCRL_RIGHT": "󰍽 ⇉"
    "&mkp LCLK": "󰍽 L"
    "&mkp RCLK": "󰍽 R"
    "&mkp MCLK": "󰍽 M"
    "&bt BT_NXT": " "
    "&bt BT_PRV": " "
    "&bt BT_CLR": " "
    "&bt BT_SEL 0": " 1"
    "&bt BT_SEL 1": " 2"
    "&bt BT_SEL 2": " 3"
    "&bt BT_SEL 3": " 4"
    "&bt BT_SEL 4": " 5"
    "&out OUT_TOG": ""
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    TAB: ""
    SPACE: "󱁐"
    RET: "󰌑"
    BSPC: "󰁮"
    DEL: "󰹾"
    LEFT: ""
    DOWN: ""
    UP: ""
    RIGHT: ""
    HOME: ""
    PG_DN: ""
    PG_UP: ""
    END: ""
    C_PLAY_PAUSE: "󰐎"
    C_NEXT: "󰒭"
    C_PREV: "󰒮"
    C_MUTE: ""
    C_VOL_UP: ""
    C_VOL_DN: ""
    C_BRI_UP: "󰃠"
    C_BRI_DN: "󰃜"
    PRINTSCREEN: ""
    SCROLLLOCK: ""
    KP_NUMLOCK: ""
    LCTRL: ⌃
    LALT: ⌥
    LGUI: ⌘
    LSHFT: ⇧
    RCTRL: ⌃
    LEFT_CONTROL: ⌃
    LEFT_ALT: ⌥
    LEFT_GUI: ⌘
    LEFT_SHFT: ⇧
    RALT: ⌥
    RGUI: ⌘
    RSHFT: ⇧
    RIGHT_CONTROL: ⌃
    RIGHT_ALT: ⌥
    RIGHT_GUI: ⌘
    RIGHT_SHFT: ⇧
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: "="
    PLUS: +
    MINUS: "-"
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: \
    BSLH: \
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON: ;
    SEMI: ;
    COLON: ":"
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ","
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT: "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"
  zmk_combos: {}
  zmk_preamble: "#define KEYMAP_DRAWER"
  zmk_additional_includes: []
